[package]
name = "pathutils"
version = "0.1.0"
authors = ["Rasmus Kildevæld <rasmuskildevaeld@gmail.com>"]
edition = "2018"

[dependencies]


[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "join"
harness = false